enum JURUSAN {
  SMA_IPA = "SMA IPA",
  SMA_IPS = "SMA IPS",
  SMA_JURUSAN_LAINNYA = "SMA JURUSAN LAINNYA",
  MA_IPA = "MA IPA",
  MA_IPS = "MA IPS",
  MA_ILMU_KEAGAMAAN = "MA ILMU KEAGAMAAN",
  MA_BAHASA = "MA BAHASA",
  MA_JURUSAN_LAINNYA = "MA JURUSAN LAINNYA",
  SMK_TEKNIK_INFORMATIKA_KOMPUTER = "SMK TEKNIK INFORMATIKA/KOMPUTER",
  SMK_TEKNIK_ELEKTRONIKA = "SMK TEKNIK ELEKTRONIKA",
  SMK_JURUSAN_LAINNYA = "SMK JURUSAN LAINNYA",
}

export default JURUSAN;
