enum TINGGI_BADAN {
  SERATUS_ENAM_PULUH_SEMBILAN = "169",
  SERATUS_TUJUH_PULUH = "170",
  SERATUS_TUJUH_PULUH_SATU = "171",
  SERATUS_TUJUH_PULUH_DUA = "172",
  SERATUS_TUJUH_PULUH_TIGA = "173",
  SERATUS_TUJUH_PULUH_EMPAT = "174",
  SERATUS_TUJUH_PULUH_LIMA = "175",
  SERATUS_TUJUH_PULUH_ENAM = "176",
  SERATUS_TUJUH_PULUH_TUJUH = "177",
  SERATUS_TUJUH_PULUH_DELAPAN = "178",
  SERATUS_TUJUH_PULUH_SEMBILAN = "179",
  SERATUS_DELAPAN_PULUH = "180"
}

export default TINGGI_BADAN;
