enum PAGES {
  HOME = "HOME",

  CHECK_KESEHATAN = "CHECK-KESEHATAN",
  CHECK_MATA = "CHECK-MATA",
  CHECK_GIGI = "CHECK-GIGI",

  RESULT = "RESULT",
  RECOMMENDATION_1 = "RECOMMENDATION-1",
}

export default PAGES;
