enum PAGES {
  HOME = "HOME",
  ABOUT = "ABOUT",

  CHECK_MATRA = "CHECK-MATRA",
  CHECK_BUTA_WARNA = "CHECK-CHECK-BUTA-WARNA",
  CHECK_MINUS = "CHECK-MINUS",

  RESULT = "RESULT",
  RECOMMENDATION_1 = "RECOMMENDATION-1",
}

export default PAGES;
